<?php

namespace common\models;

use common\behaviors\CdnUploadImageBehavior;
use Yii;
use yii\base\Model;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\helpers\ArrayHelper;
use yii\web\UploadedFile;
use yii2tech\ar\softdelete\SoftDeleteBehavior;

/**
 * This is the model class for table "businesses_story".
 *
 * @property int $id
 * @property int $businesses_id
 * @property string $year
 * @property string $title
 * @property string $texts
 * @property string $picture
 * @property int $updated_by
 * @property int $updated_at
 * @property int $created_at
 * @property int $created_by
 * @property int $deleted_at
 */
class BusinessesStory extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%businesses_story}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['year', 'title', 'texts'], 'required'],
            [['texts'], 'safe'],
            ['picture', 'image', 'extensions' => 'jpg, jpeg, png', 'maxSize' => 1024 * 1024 * 2, 'enableClientValidation' => false],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'businesses_id' => Yii::t('app', 'Businesses ID'),
            'year' => Yii::t('app', 'Year'),
            'title' => Yii::t('app', 'Title'),
            'texts' => Yii::t('app', 'Texts'),
            'picture' => Yii::t('app', 'Picture'),
            'updated_by' => Yii::t('app', 'Updated By'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'created_at' => Yii::t('app', 'Created At'),
            'created_by' => Yii::t('app', 'Created By'),
            'deleted_at' => Yii::t('app', 'Deleted At'),
        ];
    }

    /**
     * {@inheritdoc}
     * @return BusinessesStoryQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new BusinessesStoryQuery(get_called_class());
    }
    public static function handelData($eid,$defaultData = []){

        $oldIDs = ArrayHelper::map($defaultData, 'id', 'id');
        $postData = \common\models\Model::createMultiple(self::className(),$defaultData);
        Model::loadMultiple($postData, Yii::$app->request->post());
        $headlinesJson = [];
        $deletedIDs = array_diff($oldIDs, array_filter(ArrayHelper::map($postData, 'id', 'id')));

        if (! empty($deletedIDs)) {
            self::deleteAll(['id' => $deletedIDs]);
        }
        foreach ($postData as $index => $eachData) {
            $eachData->businesses_id = $eid;
            $eachData->texts = explode(PHP_EOL,$eachData->texts);
            $eachData->instanceNames = ['picture' => "BusinessesStory[{$index}][picture]"];
            if($eachData->validate()){
                $eachData->save();
            }
        }
        return true;
    }

    public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => TimestampBehavior::class
            ],
            [
                'class' => BlameableBehavior::class,
                'createdByAttribute' => 'created_by',
                'updatedByAttribute' => 'updated_by',
            ],
            'softDeleteBehavior' => [
                'class' => SoftDeleteBehavior::class,
                'softDeleteAttributeValues' => [
                    'deleted_at' => time(),
                ],
                'restoreAttributeValues' => [
                    'deleted_at' => 0,
                ],
                'replaceRegularDelete' => false, // mutate native `delete()` method
                'invokeDeleteEvents' => false
            ],
            [
                'class' => CdnUploadImageBehavior::class,
                'attribute' => 'picture',
                'scenarios' => [self::SCENARIO_DEFAULT],
                'instanceByName' => true,
                //'placeholder' => "/assets/images/default.jpg",
                'deleteBasePathOnDelete' => false,
                'createThumbsOnSave' => false,
                'transferToCDN' => true,
                'cdnPath' => "@cdnRoot/businesses",
                'basePath' => "@inceRoot/businesses",
                'path' => "@inceRoot/businesses",
                'url' => "@cdnWeb/businesses"
            ],
        ];
    }
    public function afterFind()
    {
        $this->picture = $this->getUploadUrl('picture');
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

}