<?php

namespace common\models;

use common\behaviors\CdnUploadImageBehavior;
use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "{{%businesses_investors}}".
 *
 * @property int $id
 * @property int $businesses_id
 * @property string|null $picture
 * @property string $title
 * @property string $description
 */
class BusinessesInvestors extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%businesses_investors}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'description'], 'required'],
            [['businesses_id'], 'integer'],
            [['title', 'description'], 'string', 'max' => 255],
            ['picture', 'image', 'extensions' => 'jpg, jpeg, png','enableClientValidation' => false],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'businesses_id' => Yii::t('app', 'Businesses ID'),
            'picture' => Yii::t('app', 'Picture'),
            'title' => Yii::t('app', 'Title'),
            'description' => Yii::t('app', 'Description'),
        ];
    }
    public static function handelData($eid,$defaultData = []){


        $oldIDs = ArrayHelper::map($defaultData, 'id', 'id');
        $postData = \common\models\Model::createMultiple(self::class,$defaultData);
        Model::loadMultiple($postData, Yii::$app->request->post());
        $headlinesJson = [];
        $deletedIDs = array_diff($oldIDs, array_filter(ArrayHelper::map($postData, 'id', 'id')));


        if (! empty($deletedIDs)) {
            self::deleteAll(['id' => $deletedIDs]);
        }


        foreach ($postData as $index => $eachData) {
            $eachData->businesses_id = $eid;
            $eachData->instanceNames = ['picture' => "BusinessesInvestors[{$index}][picture]"];
            if($eachData->validate()){
                $eachData->save();
            }
        }
        return true;
    }

    public function behaviors()
    {
        return [
            [
                'class' => CdnUploadImageBehavior::class,
                'attribute' => 'picture',
                'scenarios' => [self::SCENARIO_DEFAULT],
                'instanceByName' => false,
                //'placeholder' => "/assets/images/default.jpg",
                'deleteBasePathOnDelete' => false,
                'createThumbsOnSave' => false,
                'transferToCDN' => true,
                'cdnPath' => "@cdnRoot/businesses",
                'basePath' => "@inceRoot/businesses",
                'path' => "@inceRoot/businesses",
                'url' => "@cdnWeb/businesses"
            ],
        ];
    }
    public function afterFind()
    {
        $this->picture = $this->getUploadUrl('picture');
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public static function loadDefaultValue($id){
        $datas = self::find()->where(['businesses_id'=>$id])->asArray()->all();
        $arrayData = [];
        for ($i = 0; $i < count($datas); $i++) {
            $arrayData[$i] = new self();
            $arrayData[$i]->attributes = $datas[$i];
        }
        if(empty($arrayData)){
            $arrayData = [new self()];
        }
        return $arrayData;
    }

    public function canDelete()
    {
        return true;
    }
}