<?php

namespace common\models;

use common\behaviors\CdnUploadImageBehavior;
use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\helpers\ArrayHelper;
use yii2tech\ar\softdelete\SoftDeleteBehavior;

/**
 * This is the model class for table "{{%event_sponsors}}".
 *
 * @property int $id
 * @property string $event_id
 * @property string $title
 * @property string $description
 * @property string|null $picture
 * @property string|null $instagram
 * @property string|null $telegram
 * @property string|null $whatsapp
 */
class EventSponsors extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%event_sponsors}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['event_id', 'title', 'description'], 'required'],
            [['description'], 'string'],
            [['title', 'instagram', 'telegram', 'whatsapp'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'event_id' => Yii::t('app', 'Event ID'),
            'title' => Yii::t('app', 'Title'),
            'description' => Yii::t('app', 'Description'),
            'picture' => Yii::t('app', 'Picture'),
            'instagram' => Yii::t('app', 'Instagram'),
            'telegram' => Yii::t('app', 'Telegram'),
            'whatsapp' => Yii::t('app', 'Whatsapp'),
        ];
    }
    public static function handelData($eid,$defaultData = []){


        $oldIDs = ArrayHelper::map($defaultData, 'id', 'id');
        $postData = \common\models\Model::createMultiple(self::className(),$defaultData);
        Model::loadMultiple($postData, Yii::$app->request->post());
        $headlinesJson = [];
        $deletedIDs = array_diff($oldIDs, array_filter(ArrayHelper::map($postData, 'id', 'id')));


        if (! empty($deletedIDs)) {
            self::deleteAll(['id' => $deletedIDs]);
        }


        foreach ($postData as $index => $eachData) {
            $eachData->event_id = $eid;
            $eachData->instanceNames = ['picture' => "EventSponsors[{$index}][picture]"];
            if($eachData->validate()){
                $eachData->save();
            }
        }
        return true;
    }

    public function behaviors()
    {
        return [
            [
                'class' => CdnUploadImageBehavior::class,
                'attribute' => 'picture',
                'scenarios' => [self::SCENARIO_DEFAULT],
                'instanceByName' => false,
                //'placeholder' => "/assets/images/default.jpg",
                'deleteBasePathOnDelete' => false,
                'createThumbsOnSave' => false,
                'transferToCDN' => true,
                'cdnPath' => "@cdnRoot/event",
                'basePath' => "@inceRoot/event",
                'path' => "@inceRoot/event",
                'url' => "@cdnWeb/event"
            ],
        ];
    }
    public function afterFind()
    {
        $this->picture = $this->getUploadUrl('picture');
        parent::afterFind(); // TODO: Change the autogenerated stub
    }
}