<?php

namespace common\models;

use common\behaviors\CdnUploadImageBehavior;
use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "{{%mentor_services}}".
 *
 * @property int $id
 * @property int $mentor_id
 * @property string|null $picture
 * @property string $title
 * @property string $description
 */
class MentorServices extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%mentor_services}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['mentor_id', 'title', 'description'], 'required'],
            [['mentor_id'], 'integer'],
            [['description'], 'string'],
            [['title'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'mentor_id' => Yii::t('app', 'Mentor ID'),
            'title' => Yii::t('app', 'Title'),
            'description' => Yii::t('app', 'Description'),
        ];
    }
    public static function handelData($eid,$defaultData = []){


        $oldIDs = ArrayHelper::map($defaultData, 'id', 'id');
        $postData = \common\models\Model::createMultiple(self::className(),$defaultData);
        Model::loadMultiple($postData, Yii::$app->request->post());
        $headlinesJson = [];
        $deletedIDs = array_diff($oldIDs, array_filter(ArrayHelper::map($postData, 'id', 'id')));


        if (! empty($deletedIDs)) {
            self::deleteAll(['id' => $deletedIDs]);
        }


        foreach ($postData as $index => $eachData) {
            $eachData->mentor_id = $eid;
            $eachData->instanceNames = ['picture' => "MentorServices[{$index}][picture]"];
            if($eachData->validate()){
                $eachData->save();
            }
        }
        return true;
    }

    public function behaviors()
    {
        return [
            [
                'class' => CdnUploadImageBehavior::class,
                'attribute' => 'picture',
                'scenarios' => [self::SCENARIO_DEFAULT],
                'instanceByName' => false,
                //'placeholder' => "/assets/images/default.jpg",
                'deleteBasePathOnDelete' => false,
                'createThumbsOnSave' => false,
                'transferToCDN' => true,
                'cdnPath' => "@cdnRoot/mentor",
                'basePath' => "@inceRoot/mentor",
                'path' => "@inceRoot/mentor",
                'url' => "@cdnWeb/mentor"
            ],
        ];
    }
    public function afterFind()
    {
        $this->picture = $this->getUploadUrl('picture');
        parent::afterFind(); // TODO: Change the autogenerated stub
    }
}
