<?php

namespace common\models;

use common\behaviors\CdnUploadImageBehavior;
use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "{{%mentor_services}}".
 *
 * @property int $id
 * @property int $mentor_id
 * @property string|null $picture
 * @property string $title
 * @property string $description
 * @mixin CdnUploadImageBehavior
 *
 */
class MentorServices extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%mentor_services}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['mentor_id', 'title', 'description'], 'required'],
            [['mentor_id'], 'integer'],
            [['description'], 'string'],
            [['title'], 'string', 'max' => 255],
            ['picture','image', 'extensions' => 'jpg, jpeg, png','enableClientValidation' => false],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'mentor_id' => Yii::t('app', 'Mentor ID'),
            'title' => Yii::t('app', 'Title'),
            'description' => Yii::t('app', 'Description'),
        ];
    }

    public function behaviors()
    {
        return [
            [
                'class' => CdnUploadImageBehavior::class,
                'attribute' => 'picture',
                'scenarios' => [self::SCENARIO_DEFAULT],
                'instanceByName' => false,
                'deleteBasePathOnDelete' => false,
                'createThumbsOnSave' => false,
                'transferToCDN' => true,
                'cdnPath' => "@cdnRoot/mentor",
                'basePath' => "@inceRoot/mentor",
                'path' => "@inceRoot/mentor",
                'url' => "@cdnWeb/mentor"
            ],
        ];
    }
    public function afterFind()
    {
        $this->picture = $this->getUploadUrl('picture');
        parent::afterFind(); // TODO: Change the autogenerated stub
    }
}
