<?php

namespace api\models;

use common\behaviors\CdnUploadImageBehavior;
use yii\base\Model;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use yii2tech\ar\softdelete\SoftDeleteBehavior;

class ContactUs extends \common\models\ContactUs
{
    public function beforeValidate()
    {
        $this->status = 1;
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

}
