<?php

namespace api\models;


class FreelancerCreate extends Freelancer
{
    public function beforeValidate()
    {
        $this->skills =  (json_decode($this->skills));
        $this->status = Freelancer::STATUS_PENDING;
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }
}
