<?php

namespace api\models;

use common\behaviors\CdnUploadImageBehavior;
use yii\base\Model;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use yii2tech\ar\softdelete\SoftDeleteBehavior;

class Freelancer extends \common\models\Freelancer
{
    public function beforeValidate()
    {

        $this->skills =  (json_decode($this->skills));
        $this->status = 1;
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

}
