<?php

namespace api\models;

use common\behaviors\CdnUploadImageBehavior;
use yii\base\Model;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use yii2tech\ar\softdelete\SoftDeleteBehavior;

class JobResume extends \common\models\JobResume
{
    public function beforeValidate()
    {
        $this->status = 1;
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function fields()
    {
        return [
            'id',
        ];
    }
}
